### PR TITLE
Additional effects

### PR DESCRIPTION
**Pull request by Gordon-Dry**
RocketSoundEnhancement lacks a lot of configs.

Months ago I already created a branch with new effects - which are in fact clones of existing effects but better than nothing.

The problem was that I mislead the people with the name of the branch - it made people think it's only intended to be used with RealismOverhaul.
That is not true.
It's intended to be used by everyone.

So here is the new branch and PR which also contains new additions from  just today.

(WIP - I'm in the process of  creating the configs as I post this)

### CODE REVIEW

**Comment by Gordon-Dry** [comment]
This is it for now.

As I already said, the additional configs are just clones of the already existing ones.

Because I did not create them initially I'm not deeply inside of it to be able to fiddle with the configs themselves.

If anybody dares to fiddle with them to make them more realistic - go on.

**Comment by lukecologne** [comment]
So, two points. One: Is @ensou04 still active?
Two: did you include the plumes from the latest realplume releases?

**Comment by Gordon-Dry** [comment]
Two. yes, ofc, this is why it happened today ;)

**Comment by linuxgurugamer** [comment]
Just an FYI, if you look at @ensou04 's profile, you can see he hasn't been active at all for a few years

**Comment by Gordon-Dry** [comment]
> 
> 
> Just an FYI, if you look at @ensou04 's profile, you can see he hasn't been active at all for a few years

Yeah, in forum posts I always link to my repo branch.

**Comment by Gordon-Dry** [comment]
Thank you for just ignoring this.

**Comment by ensou04** [comment]
@Gordon-Dry I cant merge those configs because they are incompatible with the new system

**Comment by Gordon-Dry** [comment]
Well, they were waiting all the time before you introduced the new system.

**Pull request closed without merging**
